### PR TITLE
Adds protoc-gen-tonic and protoc-gen-prost-serde

### PR DESCRIPTION
**Pull request by mfridman**
Closes https://github.com/bufbuild/plugins/issues/96 by adding:

- [protoc-gen-tonic](https://crates.io/crates/protoc-gen-tonic)
- [protoc-gen-prost-serde](https://crates.io/crates/protoc-gen-prost-serde)

- [ ] Fix tests for plugins that rely on insertion points. Picking up the discussion in:
          - https://github.com/bufbuild/plugins/pull/255#issuecomment-1336485652
          - https://github.com/bufbuild/plugins/pull/255#issuecomment-1343014005

### CODE REVIEW

**Comment by mfridman** [comment]
I almost wonder if the simplest, and least error-prone solution here is to include:

```yaml
deps:
  - plugin: buf.build/community/neoeinstein-prost:v0.2.1
```

And then change the logic in the test to:

1. Build the plugin and the deps together
2. Modify the `buf.gen.yaml` to include those deps:

https://github.com/bufbuild/plugins/blob/201793406013425c528790c9da8dfcaba86b8c1c/tests/plugins_test.go#L29

**Comment by pkwarren** [comment]
> This would apply to all plugins, and will increase overall time to test a single plugin change. But this seems like a good property anyways, where we test the plugin with the deps. Bonus that it solves the plugin insertion problem.

I like this - seems like the most elegant solution and better reflects the behavior of plugins when run through remote packages.

**Comment by neoeinstein** [comment]
Note, protoc-gen-prost, -prost-serde, and -tonic have now published v0.2.2. Should I still look to publish a plugin to the buf plugin registry as I had previously done?

**Comment by pkwarren** [comment]
> Note, protoc-gen-prost, -prost-serde, and -tonic have now published v0.2.2. Should I still look to publish a plugin to the buf plugin registry as I had previously done?

Sorry for the delay @neoeinstein - we had to work around an issue in our tests with plugins that rely on insertion points. v0.2.2 of all of those plugins are now supported and should be rolling out to the public BSR shortly. You no longer need to worry about pushing them to the BSR - we'll maintain them going forward in this repo.

**Comment by pkwarren** [comment]
Fixed with #401.

**Pull request closed without merging**
