### PR TITLE
Add nanopb plugin

### LINKED ISSUE #683: Plugin request for Buf Schema Registry: nanopb
## Mandatory

**Where is the source code for the plugin?**

https://github.com/nanopb/nanopb

## Optional

**Does the plugin have a valid semver version?**

No

What is the latest version, and where did you get this value from?

Latest version: 0.4.7
Source: Github tags

**Does the plugin have a dependency on another plugin?**

Don’t know 

**Does the output of this plugin depend on any other external libraries?**

Don't know

### PR DESCRIPTION
**Pull request by scootermon**
Closes #683

This PR is marked as a draft because of the following open points:

1. [x] still need to successfully run the tests (ran into issues with my devcontainer setup)
2. [x] nanopb has a runtime dependency on a few c files. Since there isn't really an established library ecosystem for C (and especially not in embedded circles where you would use nanopb) we need to find an alternative like copying the files to the output. Does buf already have a way to deal with this?

### CODE REVIEW

**Review by pkwarren — COMMENTED** [review]
Looks great - just a few suggestions on the Dockerfile.

**Comment by pkwarren** [comment]
> nanopb has a runtime dependency on a few c files. Since there isn't really an established library ecosystem for C (and especially not in embedded circles where you would use nanopb) we need to find an alternative like copying the files to the output. Does buf already have a way to deal with this?

Are you talking about using this plugin as a [Generated SDK](https://buf.build/docs/bsr/generated-sdks/overview)? If so you are correct and there isn't a mechanism for C programs today. This plugin would be available initially only as a [Remote Plugin](https://buf.build/docs/bsr/remote-plugins/overview).

If you wish for the plugin itself to include additional C files in the output, it would need to ship them in the nanopg generator plugin itself using the `file` field on `CodeGeneratorResponse`: https://github.com/protocolbuffers/protobuf/blob/396d6617674622bf9be4b73088f2f17e9f6eb374/src/google/protobuf/compiler/plugin.proto#L179.

**Comment by scootermon** [comment]
> Are you talking about using this plugin as a [Generated SDK](https://buf.build/docs/bsr/generated-sdks/overview)? If so you are correct and there isn't support for C programs today. This plugin would be available initially only as a [Remote Plugin](https://buf.build/docs/bsr/remote-plugins/overview).

That's fine then, I just wanted to make sure I would add it as well in case it's already supported by nanopb.

> If you wish for the plugin itself to include additional C files in the output, it would need to ship them in the nanopg generator plugin itself using the `file` field on `CodeGeneratorResponse`

Makes sense, that's something that would have to be implemented in nanopb itself then.

---

I went ahead and applied your suggestions, updated the PR, and marked it as ready.

**Comment by mfridman** [comment]
lgtm, thanks for taking the time to contribute 🥳.

**Comment by scootermon** [comment]
Thanks guys!
You both made this a great contributing experience and I really appreciate that!

**Comment by mfridman** [comment]
Awesome, the plugin has been published via the automation in this repository to https://buf.build/community/nanopb

Took it for a spin

```yaml
# buf.gen.yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/nanopb:v0.4.8
    out: gen
```

And then generated some code

```
buf generate buf.build/acme/petapis --include-imports
```

### output

```
gen
├── google
│   └── type
│       ├── datetime.pb.c
│       ├── datetime.pb.h
│       ├── money.pb.c
│       └── money.pb.h
├── payment
│   └── v1alpha1
│       ├── payment.pb.c
│       └── payment.pb.h
└── pet
    └── v1
        ├── pet.pb.c
        └── pet.pb.h
```

**Pull request merged**
