### PR TITLE
Add planetscale-vtprotobuf remote plugin

### LINKED ISSUE #251: Plugin request for Buf Schema Registry - `protoc-gen-go-vtproto`
## Mandatory

**Where is the source code for the plugin?**

The source code for the [`protoc-gen-go-vtproto`](https://buf.build/planetscale/plugins/vtproto) plugin is found here:

https://github.com/planetscale/vtprotobuf

## Optional

**Does the plugin have a valid semver version?**

I believe so. `v0.3.0` is the latest version, taken from the GitHub tags: https://github.com/planetscale/vtprotobuf/tags

**Does this plugin have runtime dependencies?**

The only dependency is the canonical Go gRPC dependencies: `google.golang.org/grpc`

**Does the plugin have a dependency on another plugin?**

The `protoc-gen-go-vtproto` plugin depends on the base types produced by  `protoc-gen-go-grpc`.

**Do you think this plugin will be compatible with the BSR go module proxy or npm registry?**

I don't see why not, but I don't think I understand it enough to be able to say for sure.

### PR DESCRIPTION
**Pull request by pkwarren**
Fixes #251.

### CODE REVIEW

**Review by mfridman — APPROVED** [review]
lgtm, thanks @pkwarren 

@mattrobenolt. FYI the only requirement we have is a valid semver _without_ the prerelease component

**Comment by mattrobenolt** [comment]
As in, you want a 1.0+ tag? If so, I'm sure we can do that.

**Comment by mattrobenolt** [comment]
Nevermind, you merged. :)

**Comment by pkwarren** [comment]
Nope - just any version that doesn't have a prerelease or build component - any of `vMAJOR` or `vMAJOR.MINOR` or `vMAJOR.MINOR.PATCH` are accepted.

**Pull request merged**
